config:
  property:
    path: "/home/polina/Programming/MyProjects/Online-market/Online-market-back/src/main/resources/db/migration/mongo/V1__Products_Collection.json"

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: root
      password: secret
      authentication-database: admin

  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: user
    password: secret
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: 192.168.0.2:9092

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
#    prefix: /home/polina/Programming/MyProjects/Online-market/Online-market-back/src/main/resources/templates



#  security:
#    oauth2:
#      client:
#        registration:
#          facebook:
#          clientId: "715688400512285"
#          clientSecret: "936bd8e2b2a96e9027076c2ae93d81ea"
#          scope: email, public_profile





