networks:
  online-market:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/20
volumes:
  volume1:
services:
  postgres:
    image: 'postgres:15.2'
    ports:
      - '15432:5432'
    environment:
      - 'POSTGRES_USER=user'
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=secret'


  mongodb:
    container_name: mongodb-container
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=database'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'


  rabbitmq:
    container_name: rabbitmq-container
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=user'
    ports:
      - '5672:5672'


  kafka:
    image: 'bitnami/kafka:3.6.0'
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.0.2:9092
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA
    volumes:
      - volume1:/bitnami/kafka
    networks:
      online-market:
         ipv4_address: 192.168.0.2

